quarkus:
  locales: en-US
  default-locale: en-US
  http:
    port: 8080
    ssl-port: 8443
    cors: true
  log:
    category:
      "net.maisikoleni":
        level: DEBUG
  live-reload:
    #instrumentation: true
  qute:
    #suffixes: qute
net:
  maisikoleni:
    javadoc:
      search:
        libraries:
          jdk-latest:
            name: JDK 18
            description: Latest JDK Release
            base-url: https://docs.oracle.com/en/java/javase/18/docs/api/
            default: true
          junit5-latest:
            name: JUnit 5
            description: Current JUnit 5
            base-url: https://junit.org/junit5/docs/current/api/
        server:
          html:
            suggestion-count: 10
          query-char-limit: 1000
          suggestion-count-limit: 50
          log-search-threshold-nanos: 20000000
jdk:
  serialFilter: maxbytes=0