quarkus:
  locales: en-US
  default-locale: en-US
  http:
    port: 8080
    ssl-port: 8443
    cors: true
  log:
    category:
      "net.maisikoleni":
        level: DEBUG
  live-reload:
    #instrumentation: true
  qute:
    #suffixes: qute
net:
  maisikoleni:
    javadoc:
      search:
        server:
          html:
            suggestion-count: 10
          query-char-limit: 1000
          suggestion-count-limit: 50
          log-search-threshold-nanos: 20000000
jdk:
  serialFilter: maxbytes=0