quarkus:
  locales: en-US
  default-locale: en-US
  http:
    port: 8080
    cors: true
  log:
    category:
      "net.maisikoleni":
        level: DEBUG
  live-reload:
    #instrumentation: true
  qute:
    #suffixes: qute
net:
  maisikoleni:
    javadoc:
      search:
        server:
          html:
            suggestion-count: 10