quarkus:
  locales: en-US
  default-locale: en-US
  http:
    port: 8080
    ssl-port: 8443
    cors: true
    limits:
      max-body-size: 16384
      max-header-size: 8192 
    read-timeout: 10s
    idle-timeout: 10M
    body:
      handle-file-uploads: false
      uploads-directory: uploads
  log:
    category:
      "net.maisikoleni":
        level: DEBUG
  live-reload:
net:
  maisikoleni:
    javadoc:
      search:
        libraries:
          jdk-11:
            name: JDK 11
            description: JDK 11
            base-url: https://docs.oracle.com/en/java/javase/11/docs/api/
          jdk-17:
            name: JDK 17
            description: JDK 17
            base-url: https://docs.oracle.com/en/java/javase/17/docs/api/
          jdk-21:
            name: JDK 21
            description: JDK 21
            base-url: https://docs.oracle.com/en/java/javase/21/docs/api/
          jdk-latest:
            name: latest JDK (22)
            description: Latest JDK Release API
            base-url: https://docs.oracle.com/en/java/javase/22/docs/api/
            default: true
          junit5-latest:
            name: JUnit 5
            description: Current JUnit 5 API
            base-url: https://junit.org/junit5/docs/current/api/
        server:
          html:
            suggestion-count: 10
          query-char-limit: 1000
          suggestion-count-limit: 50
          log-search-threshold-nanos: 50000000
