package net.maisikoleni.javadoc.server.html.util;

import io.quarkus.qute.RawString;
import io.quarkus.qute.TemplateExtension;
import io.quarkus.qute.TemplateInstance;

/**
 * Allows to embed HTML generated by {@link TemplateInstance}s into other
 * TemplateInstances in a safe way.
 */
@TemplateExtension
public final class TemplateInstanceEmbedder {

	private TemplateInstanceEmbedder() {
	}

	public static RawString embedHtml(TemplateInstance templateInstance) {
		return new RawString(templateInstance.render());
	}
}
